### ISSUE TITLE
 No rule to make target  /libtruezip_intermediates

### ISSUE THREAD

**Issue by tlorens** [voodik/android#2]
I tried adding "CyanogenMod/android_external_libtruzip" to the manifest, and still no go.  Also there's the issue with the stupid SVOX external repo (DMCA).  Can use Google's repo in place of it.   Anyhow, this build_android.sh odroidu, doesn't complete do to the libtruezip requirements.  Not entirely sure how/where to fix it.

**Comment by giantpune** [comment]
This must have been fixed already.  just pulled and built for odroidxu3 without any issues.
